# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db7484aed48d5b76122a11c2bfce5f047f47a226c4f71e4f1a2fbb61f979baf433522f01cc1b92259edf9c53677e6a98c0e7a4bc6696a06d56f091c67418acdd

test:
  secret_key_base: a3ed90fc0722b47eae1f1db20b2ec4ea1e1d799212c0688d1b02c1d4aabb51fc47eaf595083a6ea9375f63e78787e3130e806b0dfd47ecf893ff1c4c32398e03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
